### ISSUE TITLE
If layout-file named "title_bar", this plugin will don't work

### ISSUE THREAD

**Issue by SharerMax** [avast/android-butterknife-zelezny#103]
***Problem***
If layout-file named "title_bar", this plugin will don't work. And show error message _"No IDs found in layout"_.

***Version Info***
1. Plugin Version 1.5
2. BufferKnife Version: 8.0.1
3. Android Studio Version: 2.1.2
4. System Version: Win 10 x64

**Comment by HiPipilu** [comment]
I found the same problem.It bothered me for a long time.

**Comment by JasonTsuiOfChina** [comment]
oh my god
