### ISSUE TITLE
Does this work with Android Studio 2.2 Preview Alpha 4 + ButterKnife 8.2.1?

### ISSUE THREAD

**Issue by ZakTaccardi** [avast/android-butterknife-zelezny#104]
Does this work with Android Studio 2.2 Preview Alpha 4 + ButterKnife 8.2.1?

It doesn't for me, on Mac.  (nothing appears in the command+N generated window)

**Comment by lockingroad** [comment]
me too. For studio 2.1.1+ butterknife7.0.1

**Comment by lockingroad** [comment]
uses the latest plugin  maybe can work

**Comment by geolo123** [comment]
Android ButterKnife Zelezny ， Version: 1.5.0 ， can not work in android studio 2.2 RC

**Comment by kyangc** [comment]
Can not work too.

**Comment by TomasKypta** [comment]
Please try the latest version 1.6.0 of the plugin. And also make sure the plugin is installed after AS update. The plugin should normally work with all AS versions.
