### ISSUE TITLE
don't work 

### ISSUE THREAD

**Issue by wuzhaohui026** [avast/android-butterknife-zelezny#120]
![image](https://cloud.githubusercontent.com/assets/7565399/20209087/51cc441c-a82d-11e6-8126-f15beb98311c.png)

windows7,AS 2.2.2 ,it can work before today.but today , when used it  can not be work at all.

**Comment by TomasKypta** [comment]
I guess it might have been uninstalled when Android Studio updated.
Try reinstalling the plugin.
The plugin works normally with AS 2.2.2.
