### ISSUE TITLE
butterknife @genarate not working{Error:(23, 6) error: cannot find symbol class Bind}

### ISSUE THREAD

**Issue by mdtaqi98** [avast/android-butterknife-zelezny#130]
![e1](https://cloud.githubusercontent.com/assets/25418424/24349587/204405ca-12fd-11e7-92d3-909edc2f8529.JPG)
![last problem](https://cloud.githubusercontent.com/assets/25418424/24349598/275474b2-12fd-11e7-9236-82c04ffb515a.JPG)

as seen in the image i have give the **genarate->Butterknife in setconfig in .jave file 
R.id in error 
help ,me

**Comment by mdtaqi98** [comment]
![e2](https://cloud.githubusercontent.com/assets/25418424/24366033/80d2b7dc-1335-11e7-956a-55febe6ba699.JPG)

**Comment by mdtaqi98** [comment]
This happend when click confirm it gets blank

**Comment by TomasKypta** [comment]
There's no class Bind in ButterKnife 8.x, this class was present in ButterKnife 7.x.
I cannot reproduce the problem you are having.
The plugin is correctly generating BindView annotations.

The variable names have to be valid Java variable names. Strings like "R.idBtnLogin" aren't valid variable names. That's why the input fields are red and confirm will do nothing.

**Comment by mdtaqi98** [comment]
What would be vaild ? Help me

**Comment by TomasKypta** [comment]
First try use those that the plugin propose. The input fields are pre-filled with those when you open it. 

For possible names, please check Naming section in https://docs.oracle.com/javase/tutorial/java/nutsandbolts/variables.html

**Comment by Shradhey7** [comment]
@mdtaqi98 Bro did you find the answer to your problem , if yes , then update it here because I am struggling with it . 

```
//Build.Gradle   ->
apply plugin: 'com.android.application'
//apply plugin: 'com.android.library'
//apply plugin: 'com.jakewharton.butterknife'

//External Code Starts

buildscript {
    repositories {
        google() // Gradle 4.0+
        maven { url "https://maven.google.com" } // Gradle < 4.0
        mavenCentral()
    }

    dependencies {
        classpath "com.android.tools.build:gradle:3.0.0"
        // classpath 'com.jakewharton:butterknife-gradle-plugin:8.8.1'
    }
}

// External Code Ends

android {
    compileSdkVersion 26
    buildToolsVersion '27.0.3'
    defaultConfig {
        applicationId "com.qihancloud.librarydemo"
        minSdkVersion 19
        targetSdkVersion 26
        versionCode 20170413
        versionName "1.1.7"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    productFlavors {
    }
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation 'com.android.support:appcompat-v7:26.1.0'
    implementation 'com.android.support.constraint:constraint-layout:1.1.2'

    compile 'com.jakewharton:butterknife:7.0.0'
    annotationProcessor 'com.jakewharton:butterknife-compiler:7.0.0'

    api(name: 'QihanOpenSDK_2.0.0', ext: 'aar')

}

repositories {
    flatDir {
        dirs 'libs'
    }
    google()
}

allprojects {
    repositories {
        jcenter()
    }
}
//Build.Gradle  ->
```

```
//Settings.Gradle ->
include ':QihanOpenSDK_2.0.0'
include ':jakewharton:butterknife:8.4.0'
//Settings.Gradle ->
```

Help is needed !!
