### ISSUE TITLE
It doesn't work with butterKnife 8.5.0

### ISSUE THREAD

**Issue by MrLeion** [avast/android-butterknife-zelezny#132]
It doesn't work with butterKnife 8.5.0

**Comment by yjouyang** [comment]
yep, I've seen the same problem. Android Studio doesn't show "Generate ButterKnife Injections" on the Generate menu.

**Comment by TomasKypta** [comment]
Works normally with AS 2.3.1 and ButterKnife 8.5.1.
Make sure the plugin is installed and ButterKnife is on the project classpath (the project is synced with AS).
