### ISSUE TITLE
Unable to start activity ComponentInfo{com.bt.sample.id/com.bt.sample.id.ui.activity.TicketReviewActivity}: android.view.InflateException: Binary XML file line #31: Binary XML file line #31: Error inflating class ImageView android.app.ActivityThread.performLaunchActivity  Raw Text

### ISSUE THREAD

**Issue by mukesh4u** [avast/android-butterknife-zelezny#133]
Caused by android.content.res.Resources$NotFoundException: Resource "com.bt.sample.id:drawable/banner_placeholder" (7f02005b) is not a Drawable (color or path): TypedValue{t=0x1/d=0x7f02005b a=-1 r=0x7f02005b}

Hello the above error coming in  my app but its not frequent.Out of 100 attempt 4-5 times I am getting this issue. Please let me know its solution.

**Comment by TomasKypta** [comment]
This doesn't seem related to our plugin.
