### ISSUE TITLE
Android studio v3 not working

### ISSUE THREAD

**Issue by samerzmd** [avast/android-butterknife-zelezny#145]
After adding the plugin to v3 studio the plugin stopped working and it's not showing the generate option

**Comment by tprochazka** [comment]
I'm using it on AS 3.0.0-beta6 and everything works as before.

**Comment by samerzmd** [comment]
i have uninstalled and reinstalled it but still not working , i'm using Android Studio v3.0 beta 6

**Comment by samerzmd** [comment]
i believe there was in issue in android v3 beta 6,
However in v3 beta 7 it's working
