### ISSUE TITLE
Plugin does not work for Android Studio 3

### ISSUE THREAD

**Issue by geniusplaza-kalyan** [avast/android-butterknife-zelezny#147]
The CMD + N does not show up the Generate ButterKnife Injections option

**Comment by Kml55** [comment]
Same problem

**Comment by NicolasKun** [comment]
same problem on Android Studio 3.0.0.8 
plugin ver: 1.6.0

**Comment by wapchief** [comment]
I also met this problem

**Comment by lusanyuss** [comment]
Plugin does not work for Android Studio    


I also met this problem

**Comment by lusanyuss** [comment]
Plugin does not work for Android Studio  3.0
How to solve this problem, there is a solution?

**Comment by neo1201** [comment]
Android Studio 3.0不能用了

**Comment by lusanyuss** [comment]
我家里Android studio3.0  电脑能用  但是公司的Android studio3.0  不能用   ，新建的项目也能有  老项目部能用

**Comment by yukuoyuan** [comment]
Android Studio 3.0 ButterKnife zelezny plugin not used,,,

**Comment by wapchief** [comment]
My solution is to download the official version Android Studio3.0 . Try not to use the beta

**Comment by yukuoyuan** [comment]
i am Updata in  IDE, so, It is must release!!!,but  the plugin stll not work!!!!!

**Comment by yukuoyuan** [comment]
i solved the problem ,i update the butterknife version to
    compile 'com.jakewharton:butterknife:7.0.1'

**Comment by onebee** [comment]
as 3.0 不能使用

**Comment by kimonic** [comment]
same problem!!

**Comment by charles-silva** [comment]
hi, some news for that ?

**Comment by AntonioVitiello** [comment]
Hi is there a solution to this problem? 
Zelezny plugin don't work on Android Studio 3.0

**Comment by namezsw** [comment]
Same problem, Android Studio 3.0.1

**Comment by jokermonn** [comment]
+1

**Comment by TomasKypta** [comment]
I check with Android Studio 3.0.1 and the plugin works as expected.
Make sure that the plugin is installed in AS and that ButterKnife library is on the project classpath. 
It has to be added as project dependency (both artifacts 'butterknife' and 'butterknife-compiler') and the project's Gradle build script has to be synced with AS.

**Comment by myrao** [comment]
But it's working when I using AS 3.0 on Ubuntu, then AS auto updated to 3.0.1, the plugin can't generate, and "Generate" shortcut also not display...

**Comment by Millertoken** [comment]
can not work on AS3.0.1 today.The plugin can't generate, and "Generate" shortcut also not display...

**Comment by TomasKypta** [comment]
Check your setup. Plugin works as expected.

> Make sure that the plugin is installed in AS and that ButterKnife library is on the project classpath.
> It has to be added as project dependency (both artifacts 'butterknife' and 'butterknife-compiler') and the project's Gradle build script has to be synced with AS.

**Comment by jokermonn** [comment]
when app module add butterknife dependencies, the library module can not use this plugin. u could cancel checking whether current module have add dependencies

**Comment by atikurzamanpallob** [comment]
![as](https://user-images.githubusercontent.com/19251059/36207351-c2919bf0-11bf-11e8-9ff4-5bbcf843154f.png)   place your cursor as on the image then right click on mouse then click generate
