### ISSUE TITLE
Remove Hungarian Notation from autogeneration

### ISSUE THREAD

**Issue by alexwyattdev** [avast/android-butterknife-zelezny#150]
When autogenerating codes they will automatically get the "mSomeView" naming, instead of "someView". Jake Wharton (Creator of Butterknife) also recommends avoiding this.

**Comment by TomasKypta** [comment]
The 'm' prefix is optional. You can change it in AS preferences.
Preferences > ButterKnifeZelezny > "Prefix for generated members:"
