### ISSUE TITLE
PLEASE add 'de-select all' button/checkbox to the window pane?

### ISSUE THREAD

**Issue by xbroak** [avast/android-butterknife-zelezny#36]
This is quite possibly the best productivity tool i've added to my repertoire in a long long time. Being able to instantly, not only have the boiler plate removed with Butterknife but not EVEN have to type THAT 'boilerplate' is a godsend.  

But please, Can you add the option to 'de-select' all? If that's too much trouble perhaps just stop them all being checked by default? There are so many occasions when i don't need to inject views, images/ui for example. Each an every time i find myself slowly going through the list de-selecting the ones i don't need ( the majority )

**Comment by destil** [comment]
Hi, usually when Views have ids, why not to inject them? Also already injected views are unselected.

But that one extra button wouldn't hurt. We won't develop the feature, but you are welcome to submit a pull request.

**Comment by TomasKypta** [comment]
"Select/deselect all" checkbox has been added in the latest version - 1.5.0.
