### ISSUE TITLE
Can't get this to work. Can you provide a sample app where it works?

### ISSUE THREAD

**Issue by juliomarcos** [avast/android-butterknife-zelezny#37]
Sorry, it's probably a stupid issue, but I can't make the generate Butterknife injections to appear.
Can you provide a sample app?

The one step I'm not sure that I'm following is the classpath one. 

...
dependencies {
    compile 'com.jakewharton:butterknife:6.1.0'
}

Is it correct?

**Comment by destil** [comment]
Yes the dependency is correct. Can you see the plugin in Preferences-Plugins? Are you clicking Generate while R.layout.something is selected?

But the sample app is a good idea, it's good for our testing too, I will add it.

**Comment by juliomarcos** [comment]
That's it. Selecting the R.layout.somethind did the trick. Sorry for disturbing!
Thank you!

**Comment by destil** [comment]
Let's keep this open so I won't forget the sample app.
