### ISSUE TITLE
this plugin didn't work in android studio 1.2.....

### ISSUE THREAD

**Issue by JokerHYC** [avast/android-butterknife-zelezny#41]
I couln't find your plugin in generate.....

**Comment by gostik** [comment]
I'm too

**Comment by marlowtheone** [comment]
+1

**Comment by nateridderman** [comment]
Same here on the 1.2 beta build on Windows.

**Comment by small-dream** [comment]
+1

**Comment by michalciolek** [comment]
+1

**Comment by hardikamal** [comment]
+1

**Comment by destil** [comment]
I just tried the plugin in Android Studio v1.2 RC2 and it works. Make sure you have ButterKnife library on your classpath and generating from layout reference in Activity or Fragment.

**Comment by hardikamal** [comment]
i m using stable Android studio 1.1... am able to use butterknife library manually but your plugin doesnt seems to work :(

**Comment by destil** [comment]
@hardikamal What do you mean manually? Do you have that dependency in build.gradle? Don't you see IDE exception in bottom right corner? What steps are you exactly doing?

**Comment by hardikamal** [comment]
Got it to work... had to reinstall again now its working...Thanks for the amazing plugin :)

**Comment by mattblang** [comment]
I reinstalled but still had no `generate injections` option.  I then disabled / re-enabled  and the option was back.

**Comment by yanhuasanyue1015** [comment]
+1
