### ISSUE TITLE
can we just make the variables name same with its id?

### ISSUE THREAD

**Issue by EzimetYusup** [avast/android-butterknife-zelezny#42]
can we just make the variables name same with its id like this?
  @InjectView(R.id.tv_chembirkim)
    OtkurBizTextView tv_chembirkim;
now I got this 
 @InjectView(R.id.tv_chembirkim)
    OtkurBizTextView tvChembirkim;

**Comment by destil** [comment]
I don't think so, fields with underscores are against Java/Android code conventions.
