### ISSUE TITLE
a litte opinion about ignore

### ISSUE THREAD

**Issue by wonTonx** [avast/android-butterknife-zelezny#43]
It is such a nice tool and insanely convenient,after a longtime use it I find out there sometime I gave the layout elements ids was just use to design the position in the RelativeLayout , so I won't use it in the Class, so would be so nice to add a option ignore to these elements.
And again thanks for your great work

**Comment by destil** [comment]
You can uncheck checkboxes in the dialog and elements which you don't won't won't be injected into the class.
