### ISSUE TITLE
A question of formate code

### ISSUE THREAD

**Issue by lipangit** [avast/android-butterknife-zelezny#46]
In android studio I can not found Code Style import xml.
![image](https://cloud.githubusercontent.com/assets/2038071/7222817/bee6490a-e748-11e4-843b-be42343734d7.png)
Other people on internet there is a import button.   ~.~

**Comment by destil** [comment]
Please add the file to home/Library/Preferences/AndroidStudio/codestyles/avast-android.xml, restart the AS it it should be there.
