### ISSUE TITLE
How to exclude generated some ID?

### ISSUE THREAD

**Issue by jecelyin** [avast/android-butterknife-zelezny#47]
If not, you can add it?

**Comment by tomik-dev** [comment]
You can include/exclude ids to/from generation in the dialog with the checkboxes.
Is that what you are asking? Or do you mean something else?

**Comment by jecelyin** [comment]
If there are too many of the checkbox that will be very trouble, best can directly according to ID filtering after the checkbox

**Comment by destil** [comment]
I'm not sure what you mean. Would you like another checkbox Select all/Deselect all? If so, create another issue for it.
