### ISSUE TITLE
Android Studio 1.1.0 can't use this plugin

### ISSUE THREAD

**Issue by ZhoujunAndroid** [avast/android-butterknife-zelezny#48]
android studio report log :
PluginException: cannot create class "com.codexplo.intellij.android.inject.InjectViewAction" [Plugin: com.codexplo.intellij.android]: cannot create class "com.codexplo.intellij.android.inject.InjectViewAction" [Plugin: com.codexplo.intellij.android]
14:09:46 Throwable: Null child action in group Generate () of class class com.intellij.openapi.actionSystem.DefaultActionGroup, id=InjectView

can you help me ? thx

**Comment by tomik-dev** [comment]
Hi,
the message isn't for our plugin.
It's for this plugin
https://plugins.jetbrains.com/plugin/7377
