### ISSUE TITLE
Cannot install plugin

### ISSUE THREAD

**Issue by IgorGanapolsky** [avast/android-butterknife-zelezny#49]
Hi,
I do not see a green button to install this plugin in AS 1.2.1.  Please advise.

Igor

**Comment by johnwatsondev** [comment]
In the Browse Repositories window you can install it !
<img width="412" alt="qq20150717-1" src="https://cloud.githubusercontent.com/assets/12760754/8740015/c3fa2110-2c75-11e5-93fe-bedb980ca8d4.png">

SO what's your problem? 

The last bad solution is uninstall AS and reinstall it.

Good Luck!
