### ISSUE TITLE
Android Studio 1.3 can not use this plugin

### ISSUE THREAD

**Issue by xu6148152** [avast/android-butterknife-zelezny#50]
Generate->nothing about ButterKnife

**Comment by IgorGanapolsky** [comment]
Same here. I am on Android Studio AI-141.197

**Comment by zoltanf** [comment]
Same here :(  
AS 1.3 on Mac and PC

**Comment by bkopanja** [comment]
Unfortunately the issue is still here :(

AS 1.3 AI-141.2017176 on a Mac

**Comment by yelinaung** [comment]
I can confirm this doesn't work on the Android Studio AI-141.2024585, OSX as well.

**Comment by destil** [comment]
I just tried the plugin in Android Studio v1.3 latest beta and it works. Make sure you have ButterKnife library on your classpath and generating from layout reference in Activity or Fragment.

**Comment by GeekHades** [comment]
dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.android.support:appcompat-v7:22.2.0'

    compile 'com.jakewharton:butterknife:7.0.1'//inject
}

how to reslove the question?

I  click  Generate->nothing about ButterKnife?
