### ISSUE TITLE
Support for butterknife 7

### ISSUE THREAD

**Issue by semanticer** [avast/android-butterknife-zelezny#53]
Support for butterknife 7 and it's @Bind anotation

**Comment by TheFinestArtist** [comment]
I love your plugin!
+1

**Comment by JiangDaYa0** [comment]
love it +1

**Comment by vanniktech** [comment]
+1

**Comment by destil** [comment]
Hi, it would be great to support ButterKnife 7. We are not planning working on the library in the near future. Anyone would like to do a pull request?

**Comment by tprochazka** [comment]
And ideally would be keep compatibility with older version of ButtnerKnife ;-)

**Comment by brucetoo** [comment]
+1

**Comment by ViksaaSkool** [comment]
+1 awesome plugin!

**Comment by leyou240** [comment]
+1 can't wait to use the plugin!

**Comment by cesards** [comment]
+1 !!! Thx!

**Comment by rizafu** [comment]
+1

**Comment by first087** [comment]
https://github.com/avast/android-butterknife-zelezny/pull/55

**Comment by codezjx** [comment]
+1 for support the 7!!! Thx!

**Comment by first087** [comment]
https://github.com/avast/android-butterknife-zelezny/pull/56

**Comment by tomik-dev** [comment]
Support for ButterKnife 7 (and keeping support for ButterKnife 6) was added to the latest snapshot.
It's not release yet, it will be released soon.

**Comment by tomik-dev** [comment]
Hi,
version 1.3 of the plugin with support for ButterKnife 7 was released.

**Comment by codezjx** [comment]
Thanks! It works for me perfectly!  Android Studio 1.3RC1 & Butterknife 7.0.1

**Comment by navyifanr** [comment]
+1, thx.

**Comment by l1712115388** [comment]
my heart is 碎了

**Comment by wangwenhaoandroid** [comment]
look forward this support for ButterKnife 8+
