### ISSUE TITLE
Android Studio 1.2.2 can not use this plugin

### ISSUE THREAD

**Issue by shenzhimeng** [avast/android-butterknife-zelezny#54]
Generate->nothing about ButterKnife???!!!

Before a few days can also be used!!!

**Comment by berkayturanci** [comment]
Me too.

**Comment by Onejjy** [comment]
I've the same problem here.

**Comment by tomik-dev** [comment]
Hi,
I've just checked the plugin in Android Studio 1.2.2 and it works as expected.
Make sure you have ButterKnife on the project's classpath (and that the project is synchonized with AS).
Also check that the plugin is enabled (Preferences -> Plugins -> Android ButterKnife Zelezny should be checked).

**Comment by berkayturanci** [comment]
Nope, still not working. I have tried to uninstall / install for several times, no result. I am manually using ButterKnife.

**Comment by LeXuanTien** [comment]
Android Studio 1.2.2 does not show the Generate ButterKnife Injections when first install and enabled the plugin. This can be solve by add com.jakewharton:butterknife:5.1.1 to Dependencies here (right click on App then Open Module Setting):
![image](https://cloud.githubusercontent.com/assets/3906860/8633326/b153b374-27ec-11e5-965f-da1f9c79a77b.png)

**Comment by LeXuanTien** [comment]
fixed

**Comment by Onejjy** [comment]
I've just tried to add "com.jakewharton:butterknife:5.1.1" but "com.jakewharton:butterknife:7.1.1" was allready on the list. Anyway, that do not fix the problem. 

<img width="813" alt="screen shot 2015-07-11 at 12 09 49" src="https://cloud.githubusercontent.com/assets/231661/8633390/01fd20d4-27c6-11e5-9bb1-a42154b56fea.png">

**Comment by LeXuanTien** [comment]
I just download the latest version and it is :5.1.1, I wonder what :5.1.1 and :7.1.1 mean. Did you try Clean and then Rebuild, then restart Android Studio, if it's not fixed, I have no idea.

**Comment by tomik-dev** [comment]
OK, the version of ButterKnife might explain your issues with AS 1.2.2, 
android-butterknife-zelezny currently doesn't support ButterKnife 7+ (see #53).
The latest supported version of ButterKnife is 6.10.
We are working on a fix, it should be ready soon.

So AS 1.2.2 should be working fine provided that you don't use ButterKnife 7+.

**Comment by shenzhimeng** [comment]
thanks @tomik-dev, I'm looking forward to it

**Comment by Onejjy** [comment]
Indeed, I just have tried with ButterKnife 5.1.1, and it works !
