### ISSUE TITLE
IllegalArgumentException: Argument for @NotNull parameter 'butterKnife' of com/avast/android/butterknifezelezny/navigation/NavigationMarkerProvider$ButterKnifeLink.getButterKnifeLink must not be null

### ISSUE THREAD

**Issue by vanniktech** [avast/android-butterknife-zelezny#58]
In the Event Log I get:

> IllegalArgumentException: Argument for @NotNull parameter 'butterKnife' of com/avast/android/butterknifezelezny/navigation/NavigationMarkerProvider$ButterKnifeLink.getButterKnifeLink must not be null

It seems like this plugin is doing something in the background since I get this error almost every minute.

Android Studio 1.3
Build number: AI-141.2071668
SDK Tools: 24.3.3
JRE 1.8.0_51-b16 x86_64

Is anybody else getting this?

**Comment by tomik-dev** [comment]
Hi, yes, it's bug in our plugin caused when no ButterKnife version is found on the module classpath.
Duplicates #57 
I'm working on a fix.

**Comment by vanniktech** [comment]
Ups sorry for duplicating it. Thanks!
