### ISSUE TITLE
Argument for @NotNull parameter 'butterKnife' of com/avast/android/butterknifezelezny/navigation/NavigationMarkerProvider$ButterKnifeLink.getButterKnifeLink must not be null

### ISSUE THREAD

**Issue by lsjwzh** [avast/android-butterknife-zelezny#59]
as version :  1.3 preview rc1

**Comment by johnwatsondev** [comment]
Plz update to Version 1.3.1 but it's [CRASH](https://github.com/avast/android-butterknife-zelezny/issues/60) again. So plz waiting a moment for fixing.

**Comment by tomik-dev** [comment]
This bug is fixed in 1.3.1
