### ISSUE TITLE
Menu item "generate Butterknife injections" does not show on Android studio 0.4.2

### ISSUE THREAD

**Issue by gvlekke** [avast/android-butterknife-zelezny#6]
Actions:
- installed
- android studio restart
- right click on R.layout.alayout
- choose generate
- the item "generate Butterknife injections" does not appear.

If you want more feedback I'm happy to give it to you.

**Comment by ihajat** [comment]
Your readme isn't updated. You need to specify that compile 'com.jakewharton:butterknife:7.0.1' ( or whatever version you are using) is required in the build.gradle file.

**Comment by vee-varun** [comment]
followed this link https://github.com/danielemaddaluno/Android-Update-Checker/blob/master/README.md
 to update the readme...
but didn't got the result
"_"

**Comment by raghav-blacklist1** [comment]
Hello... if you have imported the butterknife plugin and fixed gradle and still it doesn't show up then check if you have already created the viewholder class that has to be made by injection. If yes ,then delete it first.
