### ISSUE TITLE
Replace InjectView with Bind

### ISSUE THREAD

**Issue by bhaumik2712** [avast/android-butterknife-zelezny#61]
Hello !
InjectView annotation is replaced with Bind since v7.+.
(https://github.com/JakeWharton/butterknife/blob/master/CHANGELOG.md#version-700-2015-06-27)
I would be your thankful if you add support or update plugin.

Thank You.

**Comment by tomik-dev** [comment]
Support for ButterKnife 7 was already added in the latest version. 
If you have ButterKnife 7 on you classpath, it will work.

**Comment by bhaumik2712** [comment]
Just checked.
It works fine.
Thanks for the support !
