### ISSUE TITLE
Android Studio 1.3 141.2117773 with butterknife:7.0.1 can not use this plugin on OS X 10.10.4

### ISSUE THREAD

**Issue by MrCocoa** [avast/android-butterknife-zelezny#65]
Android Studio 1.3 141.2117773 with butterknife:7.0.1 can not use this plugin on OS X 10.10.4
and I have already added butterknife 7.0.1 lib on my classpath
but I can't find Generate ButterKnife Injections in Generate menu
the android-butterknife-zelezny version is 1.3.2

**Comment by matteozajac** [comment]
Doesn't work also on Windows 1.3 release

**Comment by littlethree** [comment]
i have the same problem. Doesn't work also on Windows 1.3 release

**Comment by never615** [comment]
me too

**Comment by LsBoiledWater** [comment]
idea 14 also can't work.

**Comment by Pedro-Veronezi** [comment]
me too.

**Comment by never615** [comment]
Problem solved on Windows 1.3.1 release

**Comment by littlethree** [comment]
how to solve?

**Comment by jianlei** [comment]
my android studio'version  is 1.4 Preview 3, and it does not work .

**Comment by GeekHades** [comment]
The folling way maybe is just for me, You can try it!
http://geekhades.blogspot.jp/2015/09/why-my-mac-android-studio-butterknife.html

**Comment by MrCocoa** [comment]
@GeekHades Thx so much, it works fine for me.
