### ISSUE TITLE
Generate ButterKnife Injections Not displayed in generate list

### ISSUE THREAD

**Issue by j782070772** [avast/android-butterknife-zelezny#67]
i'm sure Butterknife lib in my classpath

android studio version : 1.3.2
butterknife-zelezny version: 1.3.2

**Comment by j782070772** [comment]
change title,my english is bad

**Comment by destil** [comment]
This is a common issue, here is how to solve it: https://github.com/avast/android-butterknife-zelezny/blob/master/README.md#common-issue-the-plugin-is-not-working-after-i-updated-to-new-android-studio

**Comment by j782070772** [comment]
thanks

**Comment by Kabongosalomon** [comment]
Hi, I have the same problem how to fix it ?

**Comment by ghost** [comment]
**Windows**
1.right click on R.layout.my_layout in activity or fragment
2.Click generate(Alt+Inser)
3.Generate butterknife injection(Ctrl+Shift+B)

**Comment by JobGetabu** [comment]
above step works **## right click on R.layout.my_layout in activity or fragment**
