### ISSUE TITLE
Can you add a option that make the variable name the same as its ID?

### ISSUE THREAD

**Issue by 468122151** [avast/android-butterknife-zelezny#69]
I like Zelezny very much,however, I usually name  id  like 'hello_world_btn' , and I'd like to name the variable 'hello_world_btn' ,too.Of course , I can change  the variable name in checkbox, but if there are too many views,  it's too horrible! Can you give a option to make it better ?

**Comment by destil** [comment]
Naming variables with underscores is agains Java/Android guidelines, I don't think we will support that.

**Comment by followztx** [comment]
make same as id name?
