### ISSUE TITLE
How can add prefix "m" in bind name?

### ISSUE THREAD

**Issue by studiotang** [avast/android-butterknife-zelezny#71]
Hi, I want add prefix "m" in bind name. 
For example, the reousce id is “btn_hello",I want the bind name is "mBtnHello".

**Comment by destil** [comment]
You can set prefix in plugin settings.

**Comment by studiotang** [comment]
@destil 
Thank you, I already fix this problem.
Android Studio->File->Settings->Other Settings->ButterKnifeZelezny
