### ISSUE TITLE
Generate Butterknife Injection option is not shown in Android Studio 1.4 Stable version

### ISSUE THREAD

**Issue by abnormalbbk** [avast/android-butterknife-zelezny#72]
The plugin works in 1.3 Stable version but the option is not shown in the 1.4 Android Studio version

Settings Screenshot
![settings](https://cloud.githubusercontent.com/assets/5323624/10482736/5c1895b6-729a-11e5-9b08-c1512f599ba4.PNG)

Generate Screenshot
![genera](https://cloud.githubusercontent.com/assets/5323624/10482773/b0ed6c24-729a-11e5-9c03-5e7dc18e4911.png)

**Comment by Charrondev** [comment]
Also seeing this issue.

**Comment by hanliuxin5** [comment]
In my Android Studio(1.4) it's working...  :(

**Comment by 3mph4515** [comment]
vump
Also can't see plugin in 1.4 version:
http://i.imgur.com/19zPd74.png

**Comment by yanhuasanyue1015** [comment]
+1

**Comment by enginebai** [comment]
+1

**Comment by YoonjaeYoo** [comment]
1. Focus on the line 'setContentView(R.layout.activity_xxx);' then click 'R.layout.activity_xxx'.
2. Type "Command(Ctrl) + N"
3. It works!

**Comment by enginebai** [comment]
Yeap, the key point is clicking `R.layout.xxx`, not `setContentView()`!! It works! Thank you, @YoonjaeYoo

**Comment by abnormalbbk** [comment]
@YoonjaeYoo
Thanks for the info
It works

**Comment by gengjiawen** [comment]
+1

**Comment by nileshlg2003** [comment]
+1

**Comment by PhonHai** [comment]
why didn't work by this way?@YoonjaeYoo

**Comment by PhonHai** [comment]
why didn't work by this way?@YoonjaeYoo

**Comment by onuba** [comment]
+1 In Android studio 1.5 occurs the same problem

**Comment by onuba** [comment]
Now I can see the generate option, I had debugged a bit the code and finally I realized that the Util.isClassAvailableForPsiFile method was not able to load butterknife.InjectView from classpath.

My mistake, I had not defined well com.jakewharton:butterknife:7.0.1 so it was not in classpath. Now I see the option and is working in android studio 1.5.

**Comment by destil** [comment]
Yes the plugin works with latest AS, just make sure that butterknife is on the classpath.
