### ISSUE TITLE
why not support onlick()

### ISSUE THREAD

**Issue by vipheyue** [avast/android-butterknife-zelezny#73]
i'm got a plug from you .someone add a Features .for example ....onclick .this ia a jar .i want you to add your plug.3Q.but i don't know your email .please tell me your email .....  vipheyue@foxmail.com

**Comment by mori-honest** [comment]
It will be great to support onClick onLongClick,.... methods generators too.

**Comment by vipheyue** [comment]
https://github.com/dongjunkun/butterknife-plugin     please reference  this github project .may Reduce your workload

**Comment by destil** [comment]
Hi, you are welcome to send a pull request.

**Comment by destil** [comment]
This was just released in v1.4.0

**Comment by mori-honest** [comment]
Thanks!
Great work!

**Comment by vipheyue** [comment]
if id  in  xml is  "home_page_radio_group"    this generate var is  homepageradiogroup  . 
if this variable  equal id   will be greate  .because programmer define this id .they won't want change .
now  this android-butterknife-zelezny is power!!!!great!!

**Comment by vipheyue** [comment]
this is very useful .because i copy this  id .but this is different in activity .this make me do more work . thank you . make the  id  same with variable

**Comment by tonyshkurenko** [comment]
How to generate onClicks and other methods?

**Comment by destil** [comment]
@tonyshkurenko Just update and click Generate.

**Comment by vipheyue** [comment]
@tonyshkurenko in activity shot click R.layout.xxxxxx  . then click  Generate

**Comment by tonyshkurenko** [comment]
Ah, I see, that's just check box for onClicks. I thought it's about all listeners
