### ISSUE TITLE
In AndroidStudio beta4 on not work

### ISSUE THREAD

**Issue by YangShaoXiong** [avast/android-butterknife-zelezny#78]
![qq 20151231112738](https://cloud.githubusercontent.com/assets/7992054/12061225/6b9839ca-afbb-11e5-81da-f17ffe069786.png)

**Comment by destil** [comment]
I added explanation to this common issue here: https://github.com/avast/android-butterknife-zelezny/blob/master/README.md#common-issue-the-plugin-is-not-working-after-i-updated-to-new-android-studio
