### ISSUE TITLE
Please commit Intellij project structure to the repo

### ISSUE THREAD

**Issue by kurganec** [avast/android-butterknife-zelezny#84]
There is no .idea/modules, iml files in the repo. So I can't just clone and open the project.
Please fix gitinore according to [JetBrains.gitignore](https://github.com/github/gitignore/blob/master/Global/JetBrains.gitignore )
Please commit .idea, iml files.

**Comment by TomasKypta** [comment]
Hi, I'll check it and reconsider it.
In the meantime, we have a [wiki with setup instructions](https://github.com/avast/android-butterknife-zelezny/wiki/How-to-setup-development-environment).
