### ISSUE TITLE
Is "Inline injections" needed?

### ISSUE THREAD

**Issue by kurganec** [avast/android-butterknife-zelezny#85]
I would like to contribute "inline injections" feature?
Will you be interested? If no, I'l just create separate plugin.

**Comment by TomasKypta** [comment]
What do you mean by "inline injections"? And how is it related to Butter Knife library?

**Comment by kurganec** [comment]
replace @Bind / @InjectView with findViewById()

**Comment by TomasKypta** [comment]
We are definitely not going to support this feature.
Purpose of android-butterknife-zelezny plugin is to simplify use of [Butter Knife](http://jakewharton.github.io/butterknife/) library.
To automatically generate the boilerplate code for it.

If you need automatic generation of findViewById() method calls,
check [idea-android-studio-plugin](https://github.com/Haehnchen/idea-android-studio-plugin), I guess it does exactly what you are looking for.
