### ISSUE TITLE
Not working with Android Studio 2.0 Stable

### ISSUE THREAD

**Issue by Lollo0520** [avast/android-butterknife-zelezny#92]
Installed the plugin, but the generate butterknife injections option simply won't show up.

**Comment by dreamlivemeng** [comment]
You are using is   compile 'com.jakewharton:butterknife:8.0.0' or   compile 'com.jakewharton:butterknife:7.0.0'?

**Comment by Lollo0520** [comment]
I'm using butterknife 8.0.0.

**Comment by Lollo0520** [comment]
I'm using butterknife 8.0.0.

**Comment by dreamlivemeng** [comment]
try butterknife 7.0.0,

**Comment by TomasKypta** [comment]
Hi, butterknife 8.0.0 isn't supported right now.
We'll try to add support soon. See #93
