### ISSUE TITLE
Support for ButterKnife 8.0?

### ISSUE THREAD

**Issue by dreamlivemeng** [avast/android-butterknife-zelezny#93]
please ,Support for ButterKnife 8.0?

**Comment by ViksaaSkool** [comment]
Make Android-Butterknife-Zelezny Great Again!

**Comment by abalalovski** [comment]
Great to have it, bet they're already on it.

**Comment by TheMedo** [comment]
Can't wait!

**Comment by TomasKypta** [comment]
Hi, this is important.
We'll try to add support soon.

**Comment by dreamlivemeng** [comment]
thank you all!

**Comment by TomasKypta** [comment]
Not-yet-released

**Comment by l1712115388** [comment]
Don't support the newest version 8.0.0,but we can After the normal import packages from Maven database, manual changes app build file into low version absolutely !eg：
compile 'com.jakewharton:butterknife:7.0.1'

**Comment by TomasKypta** [comment]
Version 1.5.0 with support for ButterKnife 8.0.1 has been released.

**Comment by nishantapatil** [comment]
Thanks. Great news.
