### ISSUE TITLE
Can't Generate Butterknife Injections for new Butterknife

### ISSUE THREAD

**Issue by a1018875550** [avast/android-butterknife-zelezny#98]
the plug can't use for the new Butterknife

**Comment by TomasKypta** [comment]
Please update to version 1.5.0 of the plugin, it supports ButterKnife 8.0.1

**Comment by a1018875550** [comment]
For the  ButterKnife 8.0.1

> 
buildscript {
  repositories {
    mavenCentral()
   }
  dependencies {
    classpath 'com.neenbedankt.gradle.plugins:android-apt:1.8'
  }
}

apply plugin: 'com.neenbedankt.android-apt'
dependencies {
  apt 'com.jakewharton:butterknife-compiler:8.0.1'
}

 I need to add those?

**Comment by TomasKypta** [comment]
I meant version of Android ButterKnife Zelezny (Android Studio > Preferences > Plugins, check that version is 1.5.0). Then you need to have ButterKnife as the project dependency (and the project has to be synchroninzed with Android Studio)

**Comment by a1018875550** [comment]
thanks
