### ISSUE TITLE
Is possible to add @OnClick listener one by one.

### ISSUE THREAD

**Issue by dyguests** [avast/android-butterknife-zelezny#99]
Hello.

Could I use this plugin to this type:

``` java
    @OnClick(R.id.map_btn) void map_btn(View view) {...}

    @OnClick(R.id.private_chat_btn) void private_chat_btn(View view) {...}

    ...
```

not in a same listener.

**Comment by TomasKypta** [comment]
Hello.
The plugin currently capable to create only one `onClick` method for all views.
But yes, generating separate `onClick` methods is a good idea.
If you have time and want to contribute, pull-requests are welcome.

**Comment by dyguests** [comment]
I not sure if I can do this.I have no experience of develop plugin.
I hope I can create a pull-requests few weeks later.
:)

**Comment by siempredelao** [comment]
Hi @TomasKypta , @dyguests ! As I see there is no progress on this issue and I have some free time, I will develop this suggestion.
My idea is to add a checkbox below the "Create ViewHolder" checkbox to specify whether OnClick methods are split or should remain together.

**Comment by siempredelao** [comment]
This issue can be closed now :smiley:

**Comment by dyguests** [comment]
thanks!I'm waitting for this.
